= Transactions

Hazelcast .NET client supports transaction-aware versions of:

* Lists: {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHTxList-1.html[IHTxList<TItem>]
* Sets: {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHTxSet-1.html[IHTxSet<TItem>]
* Queues: {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHTxQueue-1.html[IHTxQueue<TItem>]
* Maps: {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHTxMap-2.html[IHTxMap<TKey, TValue>]
* Multi-maps: {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHTxMultiMap-2.html[IHTxMultiMap<TKey, TValue>]

This section documents the .NET client-side aspects of transactions. See xref:hazelcast:transactions:creating-a-transaction-interface.adoc[Transactions] in the Platform Documentation for more details.

== Transaction Management

A transaction is started through the client, which then returns an {apiDocBaseUrl}/Hazelcast.Transactions.ITransactionContext.html[ITransactionContext] instance. Transactions by default follow the Microsoft's transaction pattern: they must be disposed, and commit or roll back depending on whether they have been completed.

For example:

[source,csharp]
----
await using (var transaction = await client.BeginTransactionAsync())
{
    // ... do transaction work ...
    transaction.Complete();
}
----

Here, the transaction will commit when `transaction` is disposed, because it has been completed. Had it not been completed, it would have rolled back. Note that the explicit pattern is also supported, although less recommended:

[source,csharp]
----
var transaction = await client.BeginTransactionAsync();
// ... do transaction work ...
await transactionContext.CommitAsync();  // commmit, or...
await transactionContext.DisposeAsync(); // roll back
await transaction.DisposeAsync();
----

== Transaction-aware Objects

Transaction-aware objects are obtained from the transaction context.

For example:

[source,csharp]
----
await using (var transaction = await client.BeginTransactionAsync())
{
    var queue = await transaction.GetQueueAsync<string>("my-queue");
    var map = await transaction.GetMapAsync<string, string>("my-map");
    var set = await transaction.GetSetAsync<string>("my-set");

    try
    {
        var o = await queue.PollAsync();
        // process the object...
        await map.PutAsync("1", "value-1");
        await set.AddAsync("value");
        // do more things...

        transaction.Complete();
    }
    catch
    {
        // report the error
        // don't Complete = transaction will roll back automatically
    }
}
----

In this example, either all operations are executed, or none.

== Transaction Options

Transactions can be configured via {apiDocBaseUrl}/Hazelcast.Transactions.TransactionOptions.html[TransactionOptions] that can be passed to the {apiDocBaseUrl}/Hazelcast.IHazelcastClient.BeginTransactionAsync.html#Hazelcast_IHazelcastClient_BeginTransactionAsync_Hazelcast_Transactions_TransactionOptions_[BeginTransactionAsync(TransactionOptions)] method. These options are as follows:

* {apiDocBaseUrl}/Hazelcast.Transactions.TransactionOptions.Durability.html#Hazelcast_Transactions_TransactionOptions_Durability[Durability] a transaction is the number of members in the cluster that can take over if a member fails during a transaction commit or rollback. This value only has meaning when {apiDocBaseUrl}/Hazelcast.Transactions.TransactionOptions.Type.html#Hazelcast_Transactions_TransactionOptions_Type[Type] is `TwoPhase`.
* {apiDocBaseUrl}/Hazelcast.Transactions.TransactionOptions.Timeout.html#Hazelcast_Transactions_TransactionOptions_Timeout[Timeout] specifies the timeout of the transaction
* {apiDocBaseUrl}/Hazelcast.Transactions.TransactionOptions.Type.html#Hazelcast_Transactions_TransactionOptions_Type[Type] can be either `TwoPhase` (by default) or `OnePhase`; see xref:hazelcast:transactions:creating-a-transaction-interface.adoc[Transactions] for explanations of these values.
