// Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//   This code was generated by a tool.
//     Hazelcast Client Protocol Code Generator
//     https://github.com/hazelcast/hazelcast-client-protocol
//   Change to this file will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable IDE0051 // Remove unused private members
// ReSharper disable UnusedMember.Local
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace

using System;
using System.Collections.Generic;
using Hazelcast.Protocol.BuiltInCodecs;
using Hazelcast.Protocol.CustomCodecs;
using Hazelcast.Core;
using Hazelcast.Messaging;
using Hazelcast.Logging;
using Hazelcast.Clustering;
using Hazelcast.Serialization;
using Microsoft.Extensions.Logging;
using static Hazelcast.Messaging.Portability;

namespace Hazelcast.Protocol.Codecs
{
    /// <summary>
    /// Adds a cluster view listener to a connection.
    ///</summary>
    internal static class ClientAddClusterViewListenerServerCodec
    {
        public const int RequestMessageType = 768; // 0x000300
        public const int ResponseMessageType = 769; // 0x000301
        private const int RequestInitialFrameSize = PartitionIdFieldOffset + IntSizeInBytes;
        private const int ResponseInitialFrameSize = ResponseBackupAcksFieldOffset + ByteSizeInBytes;
        private const int MembersViewEventVersionFieldOffset = PartitionIdFieldOffset + IntSizeInBytes;
        private const int MembersViewEventInitialFrameSize = MembersViewEventVersionFieldOffset + IntSizeInBytes;
        private const int MembersViewEventMessageType = 770; // 0x000302
        private const int PartitionsViewEventVersionFieldOffset = PartitionIdFieldOffset + IntSizeInBytes;
        private const int PartitionsViewEventInitialFrameSize = PartitionsViewEventVersionFieldOffset + IntSizeInBytes;
        private const int PartitionsViewEventMessageType = 771; // 0x000303

        public sealed class RequestParameters
        {
        }

        public static ClientMessage EncodeRequest()
        {
            var clientMessage = CreateForEncode();
            clientMessage.IsRetryable = false;
            clientMessage.OperationName = "Client.AddClusterViewListener";
            var initialFrame = new Frame(new byte[RequestInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame, TypeFieldOffset, RequestMessageType);
            EncodeInt(initialFrame, PartitionIdFieldOffset, -1);
            clientMessage.Add(initialFrame);
            return clientMessage;
        }

        public static RequestParameters DecodeRequest(ClientMessage clientMessage)
        {
            var iterator = clientMessage.GetIterator();
            var request = new RequestParameters();
            //empty initial frame
            iterator.Take();
            return request;
        }

        public sealed class ResponseParameters
        {
        }

        public static ClientMessage EncodeResponse()
        {
            var clientMessage = CreateForEncode();
            var initialFrame = new Frame(new byte[ResponseInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame, TypeFieldOffset, ResponseMessageType);
            clientMessage.Add(initialFrame);
            return clientMessage;
        }

        public static ResponseParameters DecodeResponse(ClientMessage clientMessage)
        {
            var iterator = clientMessage.GetIterator();
            var response = new ResponseParameters();
            //empty initial frame
            iterator.Take();
            return response;
        }

        public static ClientMessage EncodeMembersViewEvent(int version, ICollection<Hazelcast.Data.MemberInfo> memberInfos)
        {
            var clientMessage = CreateForEncode();
            var initialFrame = new Frame(new byte[MembersViewEventInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame, TypeFieldOffset, MembersViewEventMessageType);
            EncodeInt(initialFrame, PartitionIdFieldOffset, -1);
            EncodeInt(initialFrame, MembersViewEventVersionFieldOffset, version);
            clientMessage.Add(initialFrame);
            clientMessage.Flags |= ClientMessageFlags.Event;
            ListMultiFrameCodec.Encode(clientMessage, memberInfos, MemberInfoCodec.Encode);
            return clientMessage;
        }
        public static ClientMessage EncodePartitionsViewEvent(int version, ICollection<KeyValuePair<Guid, IList<int>>> partitions)
        {
            var clientMessage = CreateForEncode();
            var initialFrame = new Frame(new byte[PartitionsViewEventInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame, TypeFieldOffset, PartitionsViewEventMessageType);
            EncodeInt(initialFrame, PartitionIdFieldOffset, -1);
            EncodeInt(initialFrame, PartitionsViewEventVersionFieldOffset, version);
            clientMessage.Add(initialFrame);
            clientMessage.Flags |= ClientMessageFlags.Event;
            EntryListUUIDListIntegerCodec.Encode(clientMessage, partitions);
            return clientMessage;
        }

        public static void HandleEvent(ClientMessage clientMessage, HandleMembersViewEvent handleMembersViewEvent, HandlePartitionsViewEvent handlePartitionsViewEvent, ILoggerFactory loggerFactory)
        {
            var messageType = clientMessage.MessageType;
            var iterator = clientMessage.GetIterator();
            if (messageType == MembersViewEventMessageType) {
                var initialFrame = iterator.Take();
                var version =  DecodeInt(initialFrame, MembersViewEventVersionFieldOffset);
                var memberInfos = ListMultiFrameCodec.Decode(iterator, MemberInfoCodec.Decode);
                handleMembersViewEvent(version, memberInfos);
                return;
            }
            if (messageType == PartitionsViewEventMessageType) {
                var initialFrame = iterator.Take();
                var version =  DecodeInt(initialFrame, PartitionsViewEventVersionFieldOffset);
                var partitions = EntryListUUIDListIntegerCodec.Decode(iterator);
                handlePartitionsViewEvent(version, partitions);
                return;
            }
            loggerFactory.CreateLogger(typeof(EventHandler)).LogDebug("Unknown message type received on event handler :" + messageType);
        }

        public delegate void HandleMembersViewEvent(int version, ICollection<Hazelcast.Data.MemberInfo> memberInfos);

        public delegate void HandlePartitionsViewEvent(int version, ICollection<KeyValuePair<Guid, IList<int>>> partitions);
    }
}