= Handling Failures (Messaging)

While sending the requests to related members, operations can fail due to various reasons. Read-only operations are retried by default. If you want to enable retry for the other operations, you can enable "redo operations" via the `hazelcast.networking.redoOperations` configuration option.

When an operation is not retried, it fails immediately with an exception.

WARNING: An operation that fails may have been performed. For instance, the client can send a queue insert operation request to the cluster, and then lose the connection. The operation will report an error, but the client cannot determine whether the cluster has received the request and processed it or not. Re-running the operation could lead to a duplicate insert.

Operations are retried for as much as `hazelcast.messaging.retryTimeoutSeconds` seconds before failing. They are initially retried without any delay, i.e., as fast as possible, for as much as `hazelcast.messaging.maxFastInvocationCount` attempts. Then, a delay is introduced between each attempt. This delay is at least `hazelcast.messaging.minRetryDelayMilliseconds` and increases after each failure; currently it is multiplied by 2 on each failure, and cannot exceed the timeout delay.

Special cases can be configured via dedicated configuration options as follows:

* When an operation fails because the underlying socket connection drops, and the operation should be retried according to the rules above, and `hazelcast.messaging.retryOnConnectionLost` is `true`, it is retried. It is possible to prevent retries only in this situation by setting the configuration option to `false`.
* When an operation fails because the client is not connected anymore, but remains active and is trying to reconnect, and the operation should be retried according to the rules above, and `hazelcast.messaging.retryOnClientReconnecting` is true, it is retried. It is possible to prevent retries only in this situation by setting the configuration option to `false`.

These configurations can be done by using the {apidocBaseUrl}/Hazelcast.Messaging.MessagingOptions.html[MessagingOptions] class, which
controls the operations between the client and each member. The following are the options provided by this class.

[cols="2,4a"]
.MessagingOptions
|===
| Option Name
| Description

|{apidocBaseUrl}/Hazelcast.Messaging.MessagingOptions.MinRetryDelayMilliseconds.html#Hazelcast_Messaging_MessagingOptions_MinRetryDelayMilliseconds[`MinRetryDelayMilliseconds`]
|Gets or sets the minimum retry delay.

|{apidocBaseUrl}/Hazelcast.Messaging.MessagingOptions.RetryUnsafeOperations.html#Hazelcast_Messaging_MessagingOptions_RetryUnsafeOperations[`RetryUnsafeOperations`]
|Whether to retry all operations including unsafe operations.

Operations can fail due to various reasons. Read-only operations are retried by default. If you want to enable retry for all operations, set this property to `true`.

However, note that a failed operation leaves the cluster in an undecided state. The cluster may have received the request and executed the operation, but failed to respond to the client. For idempotent operations this is harmless, but for non idempotent ones retrying can cause undesirable effects. Also note that the redo can perform on any member. For these reasons, the default is `false`.

|{apidocBaseUrl}/Hazelcast.Messaging.MessagingOptions.RetryTimeoutSeconds.html#Hazelcast_Messaging_MessagingOptions_RetryTimeoutSeconds[`RetryTimeoutSeconds`]
|Gets or sets the invocation timeout.

This is a soft timeout that prevents retrying an invocation for too long in case it fails. It does not control the duration of a single try, and does not abort it.
And invocation single-try can run for as long as the connection that supports it remains open.

|{apidocBaseUrl}/Hazelcast.Messaging.MessagingOptions.RetryOnClientReconnecting.html#Hazelcast_Messaging_MessagingOptions_RetryOnClientReconnecting[`RetryOnClientReconnecting`]
|Whether to retry an invocation that has failed to start because the client was offline but still active and reconnecting.

This is `true` by default, i.e., if the client got disconnected and is reconnecting, invocations are retried until they reach their timeout, or the client reconnects.
Set this to `false` if you want invocations to fail immediately in case the client gets disconnected, even if it is trying to reconnect.

Note that this only applies to invocation that failed to start, and therefore this is safe for all invocations. See `RetryUnsafeOperations` for what happens once the invocation has started.
|===




