= Distributed Objects

== Overview

Distributed objects are managed by an Hazelcast cluster, and accessed via the Hazelcast .NET client. Currently, the client supports the following distributed objects:

* `HMap` - a distributed key/value store corresponding to a server-side Map
* `HMultiMap` - a distributed key/value store corresponding to a server-side MultiMap
* `HReplicatedMap` - a distributed key/value store corresponding to a server-side ReplicatedMap
* `HList` - a distributed list store corresponding to a server-side List
* `HQueue` - a distributed queue store corresponding to a server-side Queue
* `HRingBuffer` - a distributed ring-buffer corresponding to a server-side Map
* `HSet` - a distributed set store corresponding to a server-side Set
* `HTopic` - a distributed message-publishing store corresponding to a server-side Topic

Distributed objects are obtained from the Hazelcast .NET Client and are fully identified by their unique name. If an object of the specified type and with the specified name already exists on the cluster, it is returned, otherwise it is created on the cluster:

[source,csharp]
----
var map = await client.GetMapAsync<string, string>("my-map");
----

Distributed objects should be disposed when not used, in order to release their resources. Note that this only releases client-side resources, but the actual data remain available on the cluster for further usage.

In order to wipe a distributed object entirely from the cluster, the object needs to be destroyed:

[source,csharp]
----
await map.DestroyAsync();
----

=== Object Names and Types

The name of a distributed object is unique across its type: there can only be one `HMap` object named "my_map", but there can also be an `HList` object named "my-map".

_Type_, here, means the generic definition of the type, e.g., `HMap<,>` or `HList<>`, and not the complete type, e.g., `HList<string>`.

This means that there is, in reality, one unique `HMap<,>` object named "my-map", and that the `client.GetMapAsync<string, string>("my-map")` method would refer to the exact same object as `client.GetMap<int, int>("my-map")`. The consequences of referring to an object with different types are not specified: it may work if types can be implicitly casted, and will not work if they cannot. This is not recommended.

== HMap-HMultiMap-HReplicatedMap

An `HMap` map is a distributed key/value store corresponding to a server-side map which can be considered as a distributed implementation of the well-known .NET `IDictionary<K,V>`, with data being partitioned over members of the cluster, thus providing horizontal scalability. It is one of the most important Hazelcast data structures. Additionally, Hazelcast provides the following map-related data structures:

* An `HMultiMap` map is a distributed key/value store corresponding to a server-side xref:hazelcast:data-structures:multimap.adoc[MultiMap]: a specialized map that supports storing multiple values under a single key.
* An `HReplicatedMap` map is a distributed key/value store corresponding to a server-side xref:hazelcast:data-structures:replicated-map.adoc[ReplicatedMap]: a specialized map where data is replicated to all members of the cluster, instead of being partitioned, thus providing faster read/write accesses at the cost of higher server memory consumption.

The maps' behavior can be configured on the server: see the general map xref:hazelcast:data-structures:map.adoc[documentation] for complete details about maps.

=== Defining Maps

Maps are fully identified by their type (`HMap`, `HReplicatedMap` or `HMultiMap`) and unique name, regardless of the types specified for keys and values. In other words, an `HMap<string, string>` and an `HMap<int, int>` named with the same name are backed by the same cluster structure. Obviously, referring to a map with types other than the expected types can have unspecified consequences (probably, serialization errors) and is not recommended.

Key and value types can be just about any valid .NET type, provided that they can be (de)serialized by the Hazelcast .NET Client (see the xref:serialization:overview.adoc[Serialization documentation]). They do not necessarily need to be (de)serializable by the cluster, as long as the cluster does not need to handle them as objects, and can treat them as plain binary blobs. As soon as the cluster needs to handle the objects themselves (for instance, if in-memory format is configured as `OBJECT`, or if entries are processed by entry processors), the types must also be (de)serializable by the cluster.

Because keys may never be de-serialized on the cluster, the cluster always treat them as binary blobs, for comparison purposes. That is to say, two keys are considered identical by the cluster if their serialized representations are identical.

=== Creating & Destroying Maps

A map is obtained from the Hazelcast .NET Client, and is created on-demand: if a map with the specified name already exists on the cluster, it is returned, otherwise it is created on the cluster. For instance:

[source,csharp]
----
var map = await client.GetMapAsync<string, string>("my-map");
----

Maps should be disposed after usage, in order to release their resources. Note that this only releases client-side resources, but the actual data remain available on the cluster for further usage. In order to wipe the map and its data entirely from the cluster, it needs to be destroyed:

[source,csharp]
----
await map.DestroyAsync();
----

=== Using Maps

The `HMap` structure is completely documented in the associated {apiDocBaseUrl}/Hazelcast.DistributedObjects.IHMap-2.html[`IHMap<TKey, TValue>`] reference documentation. It provides methods to manipulate entries, such as:

* `SetAsync(key, value)` and `PutAsync(key, value)` add an entry to the map
* `GetAsync(key)` retrieves the value associated with a key
* `GetKeysAsync(), `GetValuesAsync()` retrieve the keys and values
* `ContainsKeyAsync(key)`, `ContainsValueAsync(value)` determines whether the map contains a key or a value
* `GetSizeAsync()` gets the number of entries, and `IsEmptyAsync()` determines whether the map is empty
* `RemoveAsync(key)` and `DeleteAsync(key)` remove an entry

The `HMap` structure also supports locks at entry level via methods such as:

* `LockAsync(key)` locks the entry associated with the key
* `UnlockAsync(key)` unlocks an entry that was previously locked
* `IsLockedAsync(key)` determines whether an entry is locked

NOTE: Locks, due to the asynchronous aspect of the API, are not thread-based but context-based. Refer to the locking xref:using-hazelcast:locking.adoc[documentation] for complete details.

The `HMap` structure exposes events (see the xref:events.adoc[events documentation]) both at map level and at entry level. A complete list of events is provided in the {apiDocBaseUrl}/Hazelcast.DistributedObjects.MapEventHandlers-2.html[MapEventHandlers<TKey, TValue> documentation]. The following example illustrates how to subscribe, and unsubscribe, to map events:

[source,csharp]
----
var id = await map.SubscribeAsync(events => events
    .EntryRemoved((sender, args) => {
        logger.LogInformation($"Key={args.Key} / value={args.Value} removed.")
    })
    .Cleared((sender, args) => {
        logger.LogInformation("The map has been cleared.");
    }));

// ...

await map.UnsubscribeAsync(id);
----

Note that the handler methods passed to, e.g., `EntryRemoved` or `Cleared` can, be asynchronous, too.

== HList

== HQueue

== HSet

== HRingBuffer

...
...

== Transactions

In a transaction context, transactional versions of some distributed objects can be retrieved:

* `HTxList` - a transactional version of an `HList` object
* `HTxMap` - a transactional version of an `HMap` object
* `HTxMultiMap` - a transactional version of an `HMultiMap` object
* `HTxQueue` - a transactional version of an `HQueue` object
* `HTxSet` - a transactional version of an `HSet` object

See the below example.

[source,csharp]
----
using (var tx = await client.BeginTransactionAsync())
{
    using (var txmap = await tx.GetMapAsync<string, string>("my-map"))
    {
        // ...    
    }

    tx.Complete();
}
----

Transactional objects expose a subset of the methods of the original object, which are performed in a transactional way and are either committed (if the transaction is completed) or rolled back.

