site:
  title: Documentation
  url: http:localhost:5000
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: ./doc/content
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main]
    start_path: docs
  - url: https://github.com/hazelcast/cloud-docs
    branches: [main]
    start_path: docs
  - url: https://github.com/hazelcast/hz-docs
    branches: [main]
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Inlude next and previous links on each page
    page-pagination: true
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
