namespace Hazelcast.Client.Protocol
{
    /// <summary>Each exception that are defined in client protocol have unique identifier which are error code.</summary>
    /// <remarks>
    ///     Each exception that are defined in client protocol have unique identifier which are error code.
    ///     All error codes defined in protocol are listed in this class.
    /// </remarks>
    internal enum ClientProtocolErrorCodes
    {
        Undefined = 0,
        ArrayIndexOutOfBounds = 1,
        ArrayStore = 2,
        Authentication = 3,
        Cache = 4,
        CacheLoader = 5,
        CacheNotExists = 6,
        CacheWriter = 7,
        CallerNotMember = 8,
        Cancellation = 9,
        ClassCast = 10,
        ClassNotFound = 11,
        ConcurrentModification = 12,
        ConfigMismatch = 13,
        Configuration = 14,
        DistributedObjectDestroyed = 15,
        DuplicateInstanceName = 16,
        Eof = 17,
        EntryProcessor = 18,
        Execution = 19,
        Hazelcast = 20,
        HazelcastInstanceNotActive = 21,
        HazelcastOverload = 22,
        HazelcastSerialization = 23,
        Io = 24,
        IllegalArgument = 25,
        IllegalMonitorState = 26,
        IllegalState = 27,
        IllegalThreadState = 28,
        IndexOutOfBounds = 29,
        Interrupted = 30,
        InvalidAddress = 31,
        InvalidConfiguration = 32,
        MemberLeft = 33,
        NegativeArraySize = 34,
        NoSuchElement = 35,
        NotSerializable = 36,
        NullPointer = 37,
        OperationTimeout = 38,
        PartitionMigrating = 39,
        Query = 40,
        QueryResultSizeExceeded = 41,
        Quorum = 42,
        ReachedMaxSize = 43,
        RejectedExecution = 44,
        RemoteMapReduce = 45,
        ResponseAlreadySent = 46,
        RetryableHazelcast = 47,
        RetryableIo = 48,
        Runtime = 49,
        Security = 50,
        Socket = 51,
        StaleSequence = 52,
        TargetDisconnected = 53,
        TargetNotMember = 54,
        Timeout = 55,
        TopicOverload = 56,
        TopologyChanged = 57,
        Transaction = 58,
        TransactionNotActive = 59,
        TransactionTimedOut = 60,
        UriSyntax = 61,
        UtfDataFormat = 62,
        UnsupportedOperation = 63,
        WrongTarget = 64,
        Xa = 65
    }
}