// Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using Hazelcast.Protocol.BuiltInCodecs;
using Hazelcast.Protocol.CustomCodecs;
using Hazelcast.Core;
using Hazelcast.Messaging;
using Hazelcast.Logging;
using Hazelcast.Clustering;
using Hazelcast.Serialization;
using Microsoft.Extensions.Logging;
using static Hazelcast.Protocol.Portability;

// <auto-generated>
//   This code was generated by a tool.
//     Hazelcast Client Protocol Code Generator
//     https://github.com/hazelcast/hazelcast-client-protocol
//   Change to this file will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable IDE0051 // Remove unused private members

namespace Hazelcast.Protocol.CustomCodecs
{
    internal static class SimpleEntryViewCodec
    {
        private const int CostFieldOffset = 0;
        private const int CreationTimeFieldOffset = CostFieldOffset + LongSizeInBytes;
        private const int ExpirationTimeFieldOffset = CreationTimeFieldOffset + LongSizeInBytes;
        private const int HitsFieldOffset = ExpirationTimeFieldOffset + LongSizeInBytes;
        private const int LastAccessTimeFieldOffset = HitsFieldOffset + LongSizeInBytes;
        private const int LastStoredTimeFieldOffset = LastAccessTimeFieldOffset + LongSizeInBytes;
        private const int LastUpdateTimeFieldOffset = LastStoredTimeFieldOffset + LongSizeInBytes;
        private const int VersionFieldOffset = LastUpdateTimeFieldOffset + LongSizeInBytes;
        private const int TtlFieldOffset = VersionFieldOffset + LongSizeInBytes;
        private const int MaxIdleFieldOffset = TtlFieldOffset + LongSizeInBytes;
        private const int InitialFrameSize = MaxIdleFieldOffset + LongSizeInBytes;

        public static void Encode(ClientMessage clientMessage, Hazelcast.Data.Map.MapEntry<IData, IData> mapEntry)
        {
            clientMessage.Add(Frame.CreateBeginStruct());

            var initialFrame = new Frame(new byte[InitialFrameSize]);
            EncodeLong(initialFrame, CostFieldOffset, mapEntry.Cost);
            EncodeLong(initialFrame, CreationTimeFieldOffset, mapEntry.CreationTime);
            EncodeLong(initialFrame, ExpirationTimeFieldOffset, mapEntry.ExpirationTime);
            EncodeLong(initialFrame, HitsFieldOffset, mapEntry.Hits);
            EncodeLong(initialFrame, LastAccessTimeFieldOffset, mapEntry.LastAccessTime);
            EncodeLong(initialFrame, LastStoredTimeFieldOffset, mapEntry.LastStoredTime);
            EncodeLong(initialFrame, LastUpdateTimeFieldOffset, mapEntry.LastUpdateTime);
            EncodeLong(initialFrame, VersionFieldOffset, mapEntry.Version);
            EncodeLong(initialFrame, TtlFieldOffset, mapEntry.Ttl);
            EncodeLong(initialFrame, MaxIdleFieldOffset, mapEntry.MaxIdle);
            clientMessage.Add(initialFrame);

            DataCodec.Encode(clientMessage, mapEntry.Key);
            DataCodec.Encode(clientMessage, mapEntry.Value);

            clientMessage.Add(Frame.CreateEndStruct());
        }

        public static Hazelcast.Data.Map.MapEntry<IData, IData> Decode(IEnumerator<Frame> iterator)
        {
            // begin frame
            iterator.Take();

            var initialFrame = iterator.Take();
            var cost = DecodeLong(initialFrame, CostFieldOffset);
            var creationTime = DecodeLong(initialFrame, CreationTimeFieldOffset);
            var expirationTime = DecodeLong(initialFrame, ExpirationTimeFieldOffset);
            var hits = DecodeLong(initialFrame, HitsFieldOffset);
            var lastAccessTime = DecodeLong(initialFrame, LastAccessTimeFieldOffset);
            var lastStoredTime = DecodeLong(initialFrame, LastStoredTimeFieldOffset);
            var lastUpdateTime = DecodeLong(initialFrame, LastUpdateTimeFieldOffset);
            var version = DecodeLong(initialFrame, VersionFieldOffset);
            var ttl = DecodeLong(initialFrame, TtlFieldOffset);
            var maxIdle = DecodeLong(initialFrame, MaxIdleFieldOffset);

            var key = DataCodec.Decode(iterator);
            var @value = DataCodec.Decode(iterator);

            iterator.SkipToStructEnd();

            return CustomTypeFactory.CreateSimpleEntryView(key, @value, cost, creationTime, expirationTime, hits, lastAccessTime, lastStoredTime, lastUpdateTime, version, ttl, maxIdle);
        }
    }
}

#pragma warning restore IDE0051 // Remove unused private members