#
# Action: Install
#
# Installs various dependencies.
#

name: Install
inputs:
  os:
    description: The OS
    required: true
  dotnet:
    description: Whether to install .NET
    required: true
  java:
    description: Whether to install Java
    required: true

runs:
  using: "composite"
  steps:

    # Install Linux utilities
    - name: Install utilities
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        # ubuntu-latest does not have proper git installed so we have to install it
        sudo apt-get install --yes --no-install-recommends \
          git
        # we need various misc stuff
        sudo apt-get install --yes --no-install-recommends \
          wget \
          curl \
          apt-transport-https \
          software-properties-common
        # we need pwsh
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        sudo add-apt-repository universe
        sudo apt-get install -y powershell

    # Install .NET
    - name: Install .NET
      if: inputs.dotnet == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x

    # Install Java
    - name: Install JDK
      if: inputs.java == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
