//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Hazelcast .Net Client")]
[assembly: System.Reflection.AssemblyDescription("Hazelcast .Net Client ")]
[assembly: System.Reflection.AssemblyCompany("Hazelcast Inc.")]
[assembly: System.Reflection.AssemblyProduct("Hazelcast Enterprise Edition")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2008-2013, Hazelcast, Inc")]
[assembly: System.Reflection.AssemblyConfiguration("Commit 6acb142")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("2.6.6.28")]
[assembly: System.Reflection.AssemblyFileVersion("2.6.6.28")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.6.6.28")]


