// Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//   This code was generated by a tool.
//     Hazelcast Client Protocol Code Generator
//     https://github.com/hazelcast/hazelcast-client-protocol
//   Change to this file will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable IDE0051 // Remove unused private members
// ReSharper disable UnusedMember.Local
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace

using System;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Hazelcast.Protocol.BuiltInCodecs;
using Hazelcast.Protocol.CustomCodecs;
using Hazelcast.Core;
using Hazelcast.Messaging;
using Hazelcast.Clustering;
using Hazelcast.Serialization;
using Microsoft.Extensions.Logging;

namespace Hazelcast.Protocol.Codecs
{
    /// <summary>
    /// THIS MESSAGE IS NO LONGER USED BUT KEPT FOR BACKWARD COMPATIBILITY TESTS
    /// Starts execution of an SQL query.
    ///</summary>
#if SERVER_CODEC
    internal static class SqlExecute_reservedServerCodec
#else
    internal static class SqlExecute_reservedCodec
#endif
    {
        public const int RequestMessageType = 2162944; // 0x210100
        public const int ResponseMessageType = 2162945; // 0x210101
        private const int RequestTimeoutMillisFieldOffset = Messaging.FrameFields.Offset.PartitionId + BytesExtensions.SizeOfInt;
        private const int RequestCursorBufferSizeFieldOffset = RequestTimeoutMillisFieldOffset + BytesExtensions.SizeOfLong;
        private const int RequestInitialFrameSize = RequestCursorBufferSizeFieldOffset + BytesExtensions.SizeOfInt;
        private const int ResponseRowPageLastFieldOffset = Messaging.FrameFields.Offset.ResponseBackupAcks + BytesExtensions.SizeOfByte;
        private const int ResponseUpdateCountFieldOffset = ResponseRowPageLastFieldOffset + BytesExtensions.SizeOfBool;
        private const int ResponseInitialFrameSize = ResponseUpdateCountFieldOffset + BytesExtensions.SizeOfLong;

#if SERVER_CODEC
        public sealed class RequestParameters
        {

            /// <summary>
            /// Query string.
            ///</summary>
            public string Sql { get; set; }

            /// <summary>
            /// Query parameters.
            ///</summary>
            public IList<IData> Parameters { get; set; }

            /// <summary>
            /// Timeout in milliseconds.
            ///</summary>
            public long TimeoutMillis { get; set; }

            /// <summary>
            /// Cursor buffer size.
            ///</summary>
            public int CursorBufferSize { get; set; }
        }
#endif

        public static ClientMessage EncodeRequest(string sql, ICollection<IData> parameters, long timeoutMillis, int cursorBufferSize)
        {
            var clientMessage = new ClientMessage
            {
                IsRetryable = false,
                OperationName = "Sql.Execute_reserved"
            };
            var initialFrame = new Frame(new byte[RequestInitialFrameSize], (FrameFlags) ClientMessageFlags.Unfragmented);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.MessageType, RequestMessageType);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.PartitionId, -1);
            initialFrame.Bytes.WriteLongL(RequestTimeoutMillisFieldOffset, timeoutMillis);
            initialFrame.Bytes.WriteIntL(RequestCursorBufferSizeFieldOffset, cursorBufferSize);
            clientMessage.Append(initialFrame);
            StringCodec.Encode(clientMessage, sql);
            ListMultiFrameCodec.Encode(clientMessage, parameters, DataCodec.Encode);
            return clientMessage;
        }

#if SERVER_CODEC
        public static RequestParameters DecodeRequest(ClientMessage clientMessage)
        {
            using var iterator = clientMessage.GetEnumerator();
            var request = new RequestParameters();
            var initialFrame = iterator.Take();
            request.TimeoutMillis = initialFrame.Bytes.ReadLongL(RequestTimeoutMillisFieldOffset);
            request.CursorBufferSize = initialFrame.Bytes.ReadIntL(RequestCursorBufferSizeFieldOffset);
            request.Sql = StringCodec.Decode(iterator);
            request.Parameters = ListMultiFrameCodec.Decode(iterator, DataCodec.Decode);
            return request;
        }
#endif

        public sealed class ResponseParameters
        {

            /// <summary>
            /// Query ID.
            ///</summary>
            public Hazelcast.Sql.SqlQueryId QueryId { get; set; }

            /// <summary>
            /// Row metadata.
            ///</summary>
            public IList<Hazelcast.Sql.SqlColumnMetadata> RowMetadata { get; set; }

            /// <summary>
            /// Row page.
            ///</summary>
            public IList<IList<IData>> RowPage { get; set; }

            /// <summary>
            /// Whether the row page is the last.
            ///</summary>
            public bool RowPageLast { get; set; }

            /// <summary>
            /// The number of updated rows.
            ///</summary>
            public long UpdateCount { get; set; }

            /// <summary>
            /// Error object.
            ///</summary>
            public Hazelcast.Sql.SqlError Error { get; set; }
        }

#if SERVER_CODEC
        public static ClientMessage EncodeResponse(Hazelcast.Sql.SqlQueryId queryId, IList<Hazelcast.Sql.SqlColumnMetadata> rowMetadata, ICollection<ICollection<IData>> rowPage, bool rowPageLast, long updateCount, Hazelcast.Sql.SqlError error)
        {
            var clientMessage = new ClientMessage();
            var initialFrame = new Frame(new byte[ResponseInitialFrameSize], (FrameFlags) ClientMessageFlags.Unfragmented);
            initialFrame.Bytes.WriteIntL(Messaging.FrameFields.Offset.MessageType, ResponseMessageType);
            initialFrame.Bytes.WriteBoolL(ResponseRowPageLastFieldOffset, rowPageLast);
            initialFrame.Bytes.WriteLongL(ResponseUpdateCountFieldOffset, updateCount);
            clientMessage.Append(initialFrame);
            CodecUtil.EncodeNullable(clientMessage, queryId, SqlQueryIdCodec.Encode);
            ListMultiFrameCodec.EncodeNullable(clientMessage, rowMetadata, SqlColumnMetadataCodec.Encode);
            ListMultiFrameCodec.EncodeNullable(clientMessage, rowPage, ListCNDataCodec.Encode);
            CodecUtil.EncodeNullable(clientMessage, error, SqlErrorCodec.Encode);
            return clientMessage;
        }
#endif

        public static ResponseParameters DecodeResponse(ClientMessage clientMessage)
        {
            using var iterator = clientMessage.GetEnumerator();
            var response = new ResponseParameters();
            var initialFrame = iterator.Take();
            response.RowPageLast = initialFrame.Bytes.ReadBoolL(ResponseRowPageLastFieldOffset);
            response.UpdateCount = initialFrame.Bytes.ReadLongL(ResponseUpdateCountFieldOffset);
            response.QueryId = CodecUtil.DecodeNullable(iterator, SqlQueryIdCodec.Decode);
            response.RowMetadata = ListMultiFrameCodec.DecodeNullable(iterator, SqlColumnMetadataCodec.Decode);
            response.RowPage = ListMultiFrameCodec.DecodeNullable(iterator, ListCNDataCodec.Decode);
            response.Error = CodecUtil.DecodeNullable(iterator, SqlErrorCodec.Decode);
            return response;
        }

    }
}
