// Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections;
using System.Collections.Generic;
using Hazelcast.Client.Protocol;
using Hazelcast.Client.Protocol.Codec.BuiltIn;
using Hazelcast.Client.Protocol.Codec.Custom;
using Hazelcast.Client.Protocol.Util;
using Hazelcast.IO;
using Hazelcast.IO.Serialization;
using static Hazelcast.Client.Protocol.Codec.BuiltIn.FixedSizeTypesCodec;
using static Hazelcast.Client.Protocol.ClientMessage;
using static Hazelcast.IO.Bits;

namespace Hazelcast.Client.Protocol.Codec
{
    // This file is auto-generated by the Hazelcast Client Protocol Code Generator.
    // To change this file, edit the templates or the protocol
    // definitions on the https://github.com/hazelcast/hazelcast-client-protocol
    // and regenerate it.

    /// <summary>
    /// TODO DOC
    ///</summary>
    internal static class CacheManagementConfigCodec 
    {
        //hex: 0x151200
        public const int RequestMessageType = 1380864;
        //hex: 0x151201
        public const int ResponseMessageType = 1380865;
        private const int RequestIsStatFieldOffset = PartitionIdFieldOffset + IntSizeInBytes;
        private const int RequestEnabledFieldOffset = RequestIsStatFieldOffset + BoolSizeInBytes;
        private const int RequestInitialFrameSize = RequestEnabledFieldOffset + BoolSizeInBytes;
        private const int ResponseInitialFrameSize = ResponseBackupAcksFieldOffset + IntSizeInBytes;

        public class RequestParameters 
        {

            /// <summary>
            /// Name of the cache.
            ///</summary>
            public string Name;

            /// <summary>
            /// true if enabling statistics, false if enabling management.
            ///</summary>
            public bool IsStat;

            /// <summary>
            /// true if enabled, false to disable.
            ///</summary>
            public bool Enabled;

            /// <summary>
            /// the address of the host to enable.
            ///</summary>
            public com.hazelcast.nio.Address Address;
        }

        public static ClientMessage EncodeRequest(string name, bool isStat, bool enabled, com.hazelcast.nio.Address address) 
        {
            var clientMessage = CreateForEncode();
            clientMessage.IsRetryable = true;
            clientMessage.AcquiresResource = false;
            clientMessage.OperationName = "Cache.ManagementConfig";
            var initialFrame = new Frame(new byte[RequestInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame.Content, TypeFieldOffset, RequestMessageType);
            EncodeBool(initialFrame.Content, RequestIsStatFieldOffset, isStat);
            EncodeBool(initialFrame.Content, RequestEnabledFieldOffset, enabled);
            clientMessage.Add(initialFrame);
            StringCodec.Encode(clientMessage, name);
            AddressCodec.Encode(clientMessage, address);
            return clientMessage;
        }

        public static CacheManagementConfigCodec.RequestParameters DecodeRequest(ClientMessage clientMessage) 
        {
            var iterator = clientMessage.GetIterator();
            var request = new RequestParameters();
            var initialFrame = iterator.Next();
            request.IsStat =  DecodeBool(initialFrame.Content, RequestIsStatFieldOffset);
            request.Enabled =  DecodeBool(initialFrame.Content, RequestEnabledFieldOffset);
            request.Name = StringCodec.Decode(ref iterator);
            request.Address = AddressCodec.Decode(ref iterator);
            return request;
        }

        public class ResponseParameters 
        {
        }

        public static ClientMessage EncodeResponse() 
        {
            var clientMessage = CreateForEncode();
            var initialFrame = new Frame(new byte[ResponseInitialFrameSize], UnfragmentedMessage);
            EncodeInt(initialFrame.Content, TypeFieldOffset, ResponseMessageType);
            clientMessage.Add(initialFrame);

            return clientMessage;
        }

        public static CacheManagementConfigCodec.ResponseParameters DecodeResponse(ClientMessage clientMessage)
        {
            var iterator = clientMessage.GetIterator();
            var response = new ResponseParameters();
            //empty initial frame
            iterator.Next();
            return response;
        }
    }
}