name: Create Jira issue

# runs: whenever a label is added to an issue
# if: the issue title does not yet contain 'API-' and
#     the label is 'to-jira' or 'Jira'
# does: create corresponding Jira issue and link the two issues

on:
  issues:
    types: labeled

jobs:
  jira:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.issue.title, 'API-') &&
      (
        github.event.label.name == 'to-jira' ||
        github.event.label.name == 'Jira'
      )
    steps:
      - name: Call composite action
        uses: hazelcast/github-jira-tool-action@v3
        with:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          TARGET_JIRA_PROJECT: API
          JIRA_LABEL: C#
          ISSUE_TYPE: Bug
